version: "0.0.1"

targets:
  dir1:
    src: "./foo" 
    dest: "./backups/foo"
  dir2: 
    src: "/absolute/path/bar" 
    dest: "/absolute/path/backups/bar"
  dir3: 
    src: "user@remote_host:/path/" 
    dest: "../backups/remote"

    
